# Generated by Django 5.1.1 on 2024-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('categories', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('rating', models.FloatField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
            ],
        ),
    ]
